import { chromium } from 'playwright-core';
import { chromePath, GL_ARGS, launch } from './chrome.mjs';
const URL = process.argv[2] || 'https://flyover-utx.vercel.app/';
const browser = await launch(chromium);
console.log(JSON.stringify(info, null, 1));
if (errs.length) console.log('ERRORS:', errs.slice(0, 6).join(' | ')); else console.log('no page errors');
await page.screenshot({ path: 'shots/LIVE.png', timeout: 90000 });
await page.waitForTimeout(600);
await page.screenshot({ path: 'shots/LIVE.png', timeout: 90000 });
console.log('wrote shots/LIVE.png');
await browser.__done();
