# -*- coding: utf-8 -*-
"""The roofscape: what is actually ON the roofs, read off the photograph.

THE PROBLEM, stated as a measurement. This app is a FLYOVER. The camera spends
most of its time above the city looking down, so the surface the viewer sees
most is not facades — it is roofs. And `bake_detail.py` derives every roof
colour as `adjust_light(wall, -0.12)`: the roof is its own wall, 12% darker.
2,346 of the 2,453 buildings therefore render as a flat brown lid with nothing
on it. Fly West Campus and you get a field of brown lumps.

Fly the real West Campus and you get the opposite: bright white TPO membrane,
and every one of those white decks carpeted in tight rows of split-system
condensers, one per apartment. The single loudest error was never the missing
clutter — it was the COLOUR. See `docs/ROOFSCAPE.md` for the before/after.

WHAT IS FACTUAL HERE AND WHAT IS NOT. Every drawn feature carries `src`:

    src = "m"   MEASURED. Its position, size, orientation and colour are read
                off z20 Esri nadir imagery (0.129 m/px — a 1.4 m condenser is
                11 px across, which is why this works at all). The deck colour
                of every building is measured this way, without exception.
    src = "g"   GENERATED by rule, because the photograph showed nothing there.
                Only ever a stair/lift overrun, and only on buildings tall
                enough to require one. Rule, count and reasoning below.

There is no third category. Nothing here is invented decoration on a roof the
photograph says is empty.

THE VOCABULARY, derived from the imagery before anything was drawn (Playbook
rule 1 — the crops it was read off are listed in docs/ROOFSCAPE.md):

    deck     the roof surface itself, inset inside the parapet, in its OWN
             measured colour. One polygon per building. This is the pass.
    cond     a split-system condenser, ~1.4 m square, ~1.0 m tall. West Campus
             roofs carry these in paired rows of 6-14.
    unit     an AHU / large condenser / roof plant box, 5-34 m^2, ~1.7 m.
    fan      a round exhaust or cooling-tower fan. Welch's plant deck has a row
             of eight in a line.
    duct     a run of ductwork or a pipe rack: long, thin, low.
    plant    a dark equipment field or louvre screen — the big dark rectangles
             over the lab blocks. Low and wide, not a building.
    phouse   a stair/lift/mechanical penthouse: large, bright, and TALL enough
             to break the silhouette. The only kind that is ever generated.
    pool     rooftop water. Detected by colour, and there really are that many.

WHY NOT ONE BOX PER DETECTED BLOB, EVERYWHERE. Roof clutter is a per-building
cost multiplied by thousands of buildings, and the app has already auto-detected
~30 fps and dropped itself into the `performance` preset. So:
  * every feature carries `t` (LOD tier) and `d` (a keep-order in 0..1), and
    js/roofs.js splits them across two layers with different minzooms;
  * `MAX_FOR(area)` caps the clutter on any one roof, biggest kept first;
  * decks are 0.25 m tall, so they add a top face and almost no side geometry.
Measured cost is in docs/ROOFSCAPE.md. It is not free and it is not guessed.

SCOPE IS THE CORE ONLY. This reads the current snapshot, whose bbox is UT +
West Campus + The Drag (scripts/config.sh). A building outside that box gets no
deck and no clutter — it keeps the plain `rd` lid it has today. That is
deliberate: the radius pass is making the outer ring a cheap tier and it must
stay cheap. See docs/ROOFSCAPE.md "Beyond the core".

Usage:  python scripts/bake_roofscape.py [--remeasure] [--report]

  --remeasure   re-read the imagery instead of reusing data/roof_survey.json.
                Same split as bake_roofs.py, for the same reason: reading 2,400
                roofs off z20 tiles takes minutes, and the geometry — which is
                what needs iterating against renders — takes seconds.
"""
import json
import math
import os
import sys
from collections import Counter, OrderedDict

import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SNAPDIR = os.path.join(ROOT, "data", "snapshots")
TILES = os.path.join(ROOT, "data", "imagery_cache")
OUT = os.path.join(ROOT, "data", "roofscape.geojson")          # decks + tier 0
OUT_DETAIL = os.path.join(ROOT, "data", "roofscape.detail.geojson")   # tier 1, lazy
SURVEY = os.path.join(ROOT, "data", "roof_survey.json")   # what the photograph said
RUNS = os.path.join(ROOT, "data", "roof_runs.json")       # bake_roofs.py's cache
PARKING = os.path.join(ROOT, "data", "osm_cache", "parking.json")

Z = 20
M_LAT = 111320.0
RES_M = 0.13          # z20 at this latitude is 0.1289 m/px; sample at native res
RES_BIG = 0.26        # ...except on the handful of roofs over 8,000 m^2
BIG_M2 = 8000.0

# ── What gets a roof at all ───────────────────────────────────────────
MIN_H = 3.0           # a 2 m shed has no roofscape
MIN_AREA = 60.0       # below this the deck is smaller than the parapet inset
PARAPET_IN = 1.1      # deck sits this far inside the wall, so the cap reads as a rim
MIN_SAMPLES = 40      # too few pixels to trust a median
MIN_RUN_PITCHED = 2.0 # matches bake_roofs.py MIN_RUN_M — those roofs are already done

# ── Deck colour: the photograph, brought into this scene's exposure ───
# THE FIRST CUT OF THIS BAKE COPIED bake_roofs.py's deck_colour() CONSTANTS AND
# THAT WAS A MISTAKE WORTH RECORDING. That function ends in a hard ceiling on
# the brightest channel (`if mx > 150: scale down to 150`). On the handful of
# membrane decks inside a terracotta band it is a sensible guard. Applied to
# 1,847 roofs it is not a tempering, it is a FLATTENER — and the measurement
# says so:
#
#     measured off the photograph   luma p5..p95 = 122 .. 250, 912 roofs
#                                   with a channel over 200 (white TPO)
#     emitted by the first cut      luma p5..p95 = 120 .. 149, max channel
#                                   pinned at exactly 150 on over half of them
#
# Every roof in West Campus came out the same mid-tone, which is the same defect
# as the brown lids it replaced, one step lighter. So the ceiling is gone and
# what replaces it is a RANGE MAP: the photograph's luma range is rescaled onto
# the range this scene can actually show, preserving order and spread. A white
# TPO roof stays the brightest thing on the block, because in the aerial it is.
SRC_LO, SRC_HI = 112.0, 250.0   # what the photograph spans, measured
DST_LO, DST_HI = 76.0, 188.0    # what this scene spans (the stadium deck, the
                                # brightest large surface in it, sits at ~187)
DECK_DESAT = 0.25     # a nadir photo is more colourful than this scene
DECK_TOWARD = 0.04    # a trace of the building's own roof, so it belongs to it
# ...and entered COOL to land neutral. An extrusion's top face picks up the sun
# tint, so it renders warmer than the value typed here — the stadium bake
# measured a neutral #c9bdaa (R/B 1.18) coming back on screen at R/B 1.85. This
# is the same correction, at the strength the probe in
# scripts/verify/roofscape-probe.mjs measured for these decks.
DECK_COOL = 0.10
# Which pixels count as "the deck". Buildings shade their neighbours and live
# oaks overhang eaves, so a straight median measures the shadow as often as the
# roof; a straight max measures a specular hot spot. Take the median of the
# 55th-90th luma percentile band and both failures are excluded by construction.
LUMA_LO_PCT, LUMA_HI_PCT = 55, 90

# ── Equipment detection ───────────────────────────────────────────────
BG_M = 4.2            # local window: bigger than any unit, smaller than a roof
DEV_K = 2.9           # robust threshold, in MADs of the local deviation
DEV_FLOOR = 9.0       # ...but never less sensitive than this many luma levels
# ...and never LESS sensitive than this, which is the fix for a real feedback
# bug. The threshold adapts to each roof's own MAD, so a roof densely carpeted
# in condensers — a West Campus apartment block, i.e. exactly the roof this pass
# exists for — raises its own threshold and detects the fewest units. The first
# cut found a median of 2 blobs per building and 18 on roofs over 800 m^2, where
# the aerial plainly shows 60 to 120. Capping the adaptive term breaks the loop.
DEV_CEIL = 26.0
VEG_SAT = 0.13        # a green, saturated blob is a live oak over the eave, not plant
MIN_BLOB_M2 = 0.6
# How many blobs the SURVEY keeps. Deliberately far more than any roof will
# draw: the drawn cap is applied in the geometry stage (MAX_FOR), so it can be
# retuned in seconds against the cache instead of a 20-minute re-read.
SURVEY_KEEP = 130

# The classifier. Read off the crops listed in docs/ROOFSCAPE.md, then checked
# against them. Heights are the one generative number in each row: a nadir photo
# cannot measure height, so each kind gets the height that kind of plant has.
KIND_H = {"cond": 1.0, "unit": 1.7, "fan": 2.1, "duct": 0.9,
          "plant": 1.5, "phouse": 3.0, "pool": 0.12}
# Fallback colours, used only when a blob's own pixels are too dark to trust
# (a unit sitting in its own shadow reads near-black and would paint a hole).
KIND_COL = {"cond": "#8e8b84", "unit": "#a09c93", "fan": "#8a887f", "duct": "#a8a49a",
            "plant": "#5f5d58", "phouse": "#b0aa9e", "pool": "#4f8ea8"}
DARK_FLOOR = 46       # below this median luma, use the fallback instead

# WATER, AND WHY THE FIRST CUT FOUND 1,052 SWIMMING POOLS. "Blue" is not a water
# test in aerial imagery: a shadow is lit by the SKY, so every shadow on every
# roof has B > R. The survey's water mask is deliberately permissive and the
# decision is made HERE, against what the blobs actually turned out to be:
#
#     the median "pool" it found   2.6 m^2, luma 81, B-R 22   <- a shadow sliver
#     what a real pool looks like  >= 8 m^2, bright, strongly blue
#
# Requiring all three at once takes 1,052 down to about 70, which is roughly how
# many rooftop and courtyard pools West Campus and the campus actually have.
# These thresholds live in the geometry stage on purpose: re-deciding them costs
# seconds against the cached survey instead of a 20-minute re-read.
POOL_MIN_M2 = 7.0
POOL_MIN_LUMA = 92.0
POOL_MIN_BR = 20.0

# ── The one generated kind ────────────────────────────────────────────
# A building tall enough to need a lift needs somewhere to terminate it. Where
# the photograph shows a roof with no structure on it at all AND the building is
# at least this tall, one overrun is placed. Everything about it except its
# existence is a rule: size, and a corner picked from a hash of the building id
# so it is stable across bakes.
OVERRUN_MIN_H = 11.0      # ~4 storeys; below that a roof hatch does the job
OVERRUN_W, OVERRUN_L, OVERRUN_HT = 4.6, 3.8, 2.8

# ── Buildings whose footprint is corrected AFTER this bake reads it ───
# js/union24.js replaces the Union on 24th's geometry at load time: the snapshot
# has it as one solid quad, and the app draws an H-plan with a 36 m open court,
# at a 94.4 m parapet rather than the baked 97.5. A deck baked from the snapshot
# would be the wrong SHAPE (a slab across the court) at the wrong HEIGHT.
#
# The fix is not to re-derive the H-plan here. That would put the hero build's
# measured geometry in two files that can silently diverge — the exact failure
# app.js documents for CAP_GEOM. And union24.js already makes a considered call
# on this roof (`rd: '#8a8b8c'  // roof = L29 amenity deck + mechanical`), which
# a generic bake would overwrite with something worse. So it is skipped, and the
# Union's rooftop stays a hero job. See docs/ROOFSCAPE.md "Known gaps".
FOOTPRINT_OVERRIDDEN = {"Union on 24th"}

# How many blobs are actually DRAWN on one roof. A flat cap is the wrong shape:
# 46 units is nothing on a 7,000 m^2 apartment block and far too many on a
# 200 m^2 shopfront. Scaling with area keeps the DENSITY roughly constant, which
# is what the eye reads, and the biggest are kept first so what survives is what
# shows from the air. The `d` keep-order then lets the density knob thin these
# further at run time without a re-bake.
def MAX_FOR(area_m2):
    return int(max(10, min(96, area_m2 / 85.0)))


# LOD. `t=0` is what reads from flying altitude and draws from z14.5; `t=1` is
# the small stuff and waits until you are close enough for it to be information
# rather than noise. Tier is decided by SIZE, not by kind — a big condenser
# bank reads from the air and a small penthouse does not.
TIER0_M2 = 11.0
# Two same-kind boxes at the same height sharing more than this fraction of the
# smaller one's area are one object detected twice. 0.35 rather than something
# near 1.0 because the two halves of a split louvre screen come back as two
# rectangles that each also cover the gap, so the pair overlaps substantially
# without either containing the other.
COPLANAR_COVER = 0.35
# ...and when they overlap by LESS than that, they are two real objects that
# abut. Lift the later one by this much rather than deleting it.
COPLANAR_STAGGER = 0.25
TIER0_HT = 2.4


# ── tiles ─────────────────────────────────────────────────────────────
_cache = OrderedDict()
_CACHE_MAX = 320          # 320 * 256*256*3 = 63 MB; the full set would be 800 MB


def tile(xt, yt):
    k = (xt, yt)
    if k in _cache:
        _cache.move_to_end(k)
        return _cache[k]
    p = os.path.join(TILES, "%d_%d_%d.jpg" % (Z, xt, yt))
    a = np.asarray(Image.open(p).convert("RGB")) if os.path.exists(p) else None
    _cache[k] = a
    if len(_cache) > _CACHE_MAX:
        _cache.popitem(last=False)
    return a


def sample(lons, lats):
    """Vectorised nadir sample. Returns (RGB uint8 array, ok mask)."""
    n = 2.0 ** Z
    xf = (lons + 180.0) / 360.0 * n
    yf = (1.0 - np.arcsinh(np.tan(np.radians(lats))) / np.pi) / 2.0 * n
    xt = np.floor(xf).astype(np.int64)
    yt = np.floor(yf).astype(np.int64)
    px = np.clip(((xf - xt) * 256).astype(np.int64), 0, 255)
    py = np.clip(((yf - yt) * 256).astype(np.int64), 0, 255)
    out = np.zeros(lons.shape + (3,), np.uint8)
    ok = np.zeros(lons.shape, bool)
    # np.unique on a packed key, not set(zip(...tolist())): the latter builds two
    # million Python ints for one large roof, and it showed up as the bake
    # apparently hanging around building 600.
    key = xt.astype(np.int64) * (1 << 22) + yt.astype(np.int64)
    for k in np.unique(key):
        a = int(k >> 22); b = int(k & ((1 << 22) - 1))
        arr = tile(a, b)
        if arr is None:
            continue
        m = key == k
        out[m] = arr[py[m], px[m]]
        ok[m] = True
    return out, ok


# ── geometry helpers (same conventions as bake_roofs.py) ──────────────
def to_m(ring, lat0):
    k = math.cos(math.radians(lat0))
    return [(p[0] * M_LAT * k, p[1] * M_LAT) for p in ring]


def to_ll(pts, lat0):
    k = math.cos(math.radians(lat0))
    return [[round(x / (M_LAT * k), 6), round(y / M_LAT, 6)] for (x, y) in pts]


def signed_area(pts):
    a = 0.0
    for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
        a += x0 * y1 - x1 * y0
    return a * 0.5


def clean(pts):
    p = pts[:-1] if pts and pts[0] == pts[-1] else pts[:]
    out = []
    for q in p:
        if not out or math.hypot(q[0] - out[-1][0], q[1] - out[-1][1]) > 0.05:
            out.append(q)
    if len(out) > 2 and math.hypot(out[0][0] - out[-1][0], out[0][1] - out[-1][1]) <= 0.05:
        out.pop()
    return out


def ccw(pts):
    p = pts[:-1] if pts and pts[0] == pts[-1] else pts[:]
    return p if signed_area(p + [p[0]]) >= 0 else p[::-1]


def inset(pts, d):
    """Offset a closed CCW ring inward by d metres. None when it degenerates.

    Lifted from bake_roofs.py rather than imported, because that file is a
    script with a main() and importing it would run the roof bake.
    """
    p = ccw(pts)
    n = len(p)
    if n < 3:
        return None
    lines = []
    for i in range(n):
        x0, y0 = p[i]
        x1, y1 = p[(i + 1) % n]
        dx, dy = x1 - x0, y1 - y0
        L = math.hypot(dx, dy)
        if L < 1e-9:
            return None
        nx, ny = dy / L, -dx / L
        lines.append((x0 - nx * d, y0 - ny * d, dx, dy))
    out = []
    for i in range(n):
        ax, ay, adx, ady = lines[i - 1]
        bx, by, bdx, bdy = lines[i]
        den = adx * bdy - ady * bdx
        if abs(den) < 1e-9:
            return None
        t = ((bx - ax) * bdy - (by - ay) * bdx) / den
        out.append((ax + adx * t, ay + ady * t))
    if signed_area(out + [out[0]]) <= 1.0:
        return None
    for (x, y), (x0, y0) in zip(out, p):
        if math.hypot(x - x0, y - y0) > abs(d) * 6 + 3:
            return None
    return out


def poly_mask(ring, X, Y):
    """Vectorised even-odd point-in-polygon over a grid.

    The scan uses the ROW coordinate only, so it is done once per row rather
    than once per cell: a 700 x 1000 grid against a 300-vertex footprint is
    300 x 700,000 cell tests the naive way, and that is what made the first run
    look like it had hung. Here it is 300 x 700 row tests plus one comparison
    per cell.
    """
    ys = Y[:, 0]
    xs = X[0, :]
    inside = np.zeros((ys.size, xs.size), bool)
    n = len(ring)
    for i in range(n):
        x0, y0 = ring[i]
        x1, y1 = ring[(i + 1) % n]
        if y0 == y1:
            continue
        cond = (y0 > ys) != (y1 > ys)
        if not cond.any():
            continue
        xint = x0 + (ys - y0) / (y1 - y0) * (x1 - x0)
        inside[cond] ^= xs[None, :] < xint[cond, None]
    return inside


def dominant_axis(ring):
    """Azimuth of the longest edge, in radians. Roof plant is laid out square to
    the building, never to north — so every box is placed in this frame."""
    best, th = 0.0, 0.0
    n = len(ring)
    for i in range(n):
        x0, y0 = ring[i]
        x1, y1 = ring[(i + 1) % n]
        L = math.hypot(x1 - x0, y1 - y0)
        if L > best:
            best, th = L, math.atan2(y1 - y0, x1 - x0)
    return th % (math.pi / 2)      # a rectangle's four edges are one frame


def clearance(p, poly):
    def seg(pt, a, b):
        dx, dy = b[0] - a[0], b[1] - a[1]
        L2 = dx * dx + dy * dy
        t = 0.0 if L2 < 1e-12 else max(0.0, min(1.0, ((pt[0]-a[0])*dx + (pt[1]-a[1])*dy) / L2))
        return math.hypot(pt[0] - (a[0] + dx*t), pt[1] - (a[1] + dy*t))
    return min(seg(p, a, b) for a, b in zip(poly, poly[1:] + poly[:1]))


# ── colour ────────────────────────────────────────────────────────────
def hex_of(rgb):
    return "#" + "".join("%02x" % int(round(max(0, min(255, c)))) for c in rgb)


def temper(rgb, parent, toward=DECK_TOWARD, dst=(DST_LO, DST_HI), cool=DECK_COOL):
    """Bring a photographed colour into this scene's exposure. See DECK_* above.

    Order matters: rescale LUMA first (so the range map is not fighting the
    desaturation), then pull the chroma in, then the cool bias, then the trace
    of the parent. Desaturating first and rescaling after would compress the
    bright end again, which is the bug this replaced.
    """
    c = np.asarray(rgb, dtype=float)
    lum = float(0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2])
    t = min(1.0, max(0.0, (lum - SRC_LO) / (SRC_HI - SRC_LO)))
    tgt = dst[0] + (dst[1] - dst[0]) * t
    c = c * (tgt / max(lum, 1e-3))
    g = float(c.mean())
    c = c + (g - c) * DECK_DESAT
    if cool:
        c = c * np.array([1.0 - cool * 0.55, 1.0, 1.0 + cool])
    if parent and len(parent) == 7 and toward > 0:
        pc = np.array([int(parent[i:i+2], 16) for i in (1, 3, 5)], dtype=float)
        c = c * (1 - toward) + pc * toward
    return hex_of(np.clip(c, 0, 255))


def like(hexcol, src, dst, lo=0.05, hi=1.8):
    """Move a colour the way the building's own roof colour moves between hours.

    Same function as bake_roofs.py. It is what stops a measured deck from
    drifting out of the palette the rest of the scene lives in at golden hour
    and at night — rather than inventing a second and third measurement.
    """
    if not (hexcol and src and dst) or len(hexcol) != 7 or len(src) != 7 or len(dst) != 7:
        return hexcol
    out = []
    for i in (1, 3, 5):
        c = int(hexcol[i:i+2], 16)
        s = max(1, int(src[i:i+2], 16))
        d = int(dst[i:i+2], 16)
        out.append(max(0, min(255, int(round(c * max(lo, min(hi, d / s)))))))
    return "#" + "".join("%02x" % c for c in out)


def night_of(deck_hex, parent_rn):
    """A roof at night is NOT a bright roof scaled down.

    The first cut used `like()` for all three hours. That works for golden hour,
    where the two ends are a similar brightness. At NIGHT it does not, because
    the day->night ratio gets applied to a deck that may be twice as bright as
    the `rd` the ratio was derived from — so the brighter the roof, the brighter
    it stayed, and that ratio's strongest channel is blue. Measured:

        deck night luma   p50 27.0   p95 40.0   max 54.7   B/R 2.49
        wall night luma   p50 33.6   p95 37.6
        building rn luma  p50 18.7   p95 27.7   B/R 1.81

    i.e. the brightest roofs out-shone the WALLS, and West Campus read as a
    field of glowing blue lids from the air. That is the inverted-silhouette
    failure `scripts/verify/night-silhouette.mjs` exists to catch, and the
    stadium bake records the same lesson for its seating deck ("the night values
    are deliberately as dark as a night WALL").

    An unlit membrane roof at night is dark. So the night colour is the
    building's own already-tuned `rn`, modulated only mildly by how bright this
    deck is in daylight — the sqrt compresses a 2.2x daylight range to about
    1.3x — so a white TPO roof still reads a shade lighter than a tar roof
    without either becoming a light source.
    """
    if not (parent_rn and len(parent_rn) == 7 and deck_hex and len(deck_hex) == 7):
        return parent_rn or deck_hex
    d = [int(deck_hex[i:i + 2], 16) for i in (1, 3, 5)]
    n = np.array([int(parent_rn[i:i + 2], 16) for i in (1, 3, 5)], dtype=float)
    dl = 0.299 * d[0] + 0.587 * d[1] + 0.114 * d[2]
    rel = min(1.30, max(0.80, math.sqrt(max(dl, 1.0) / ((DST_LO + DST_HI) / 2.0))))
    return hex_of(np.clip(n * rel, 0, 255))


# ── the survey: read one roof off the photograph ──────────────────────
def survey(ring_ll, lat0, parent_rd, is_parking):
    """Measure one footprint. Returns None when the imagery cannot answer.

    Everything in the returned dict is in metres relative to the ring's own
    centroid, in the building's own axis frame — so the geometry stage can be
    re-run against a different pitch or height without re-reading a tile.
    """
    pm = clean(to_m(ring_ll, lat0))
    if len(pm) < 3:
        return None
    poly = ccw(pm)
    area = abs(signed_area(poly + [poly[0]]))
    if area < MIN_AREA:
        return None
    deck = inset(pm, PARAPET_IN) or inset(pm, 0.55)
    if deck is None:
        return None
    deck = ccw(deck)

    cx = sum(p[0] for p in deck) / len(deck)
    cy = sum(p[1] for p in deck) / len(deck)
    xs = [p[0] for p in deck]; ys = [p[1] for p in deck]
    res = RES_M if area < BIG_M2 else RES_BIG
    gx = np.arange(min(xs), max(xs) + res, res)
    gy = np.arange(min(ys), max(ys) + res, res)
    if gx.size < 4 or gy.size < 4 or gx.size * gy.size > 6_000_000:
        return None
    X, Y = np.meshgrid(gx, gy)
    inside = poly_mask(deck, X, Y)
    if inside.sum() < MIN_SAMPLES:
        return None

    k = math.cos(math.radians(lat0))
    rgb, ok = sample(X / (M_LAT * k), Y / M_LAT)
    good = inside & ok
    if good.sum() < MIN_SAMPLES:
        return None

    f = rgb.astype(np.float32)
    luma = 0.299 * f[..., 0] + 0.587 * f[..., 1] + 0.114 * f[..., 2]

    # ── deck colour ───────────────────────────────────────────────────
    lv = luma[good]
    lo, hi = np.percentile(lv, [LUMA_LO_PCT, LUMA_HI_PCT])
    band = good & (luma >= lo) & (luma <= hi)
    if band.sum() < 12:
        band = good
    col = np.median(f[band], axis=0)
    tex = float(np.std(lv) / 255.0)      # gravel ballast is rough, TPO is smooth

    out = {"col": [round(float(c), 1) for c in col], "tex": round(tex, 4),
           "n": int(good.sum()), "area": round(area, 1),
           "c": [round(cx, 2), round(cy, 2)], "blobs": []}

    # ── equipment ─────────────────────────────────────────────────────
    # A roof unit is a LOCAL deviation, not an absolute brightness: a dark
    # condenser on white TPO and a white AHU on black tar are the same event.
    # So subtract a local median wider than any unit and threshold what is left,
    # in MADs, so a smooth membrane and a rough gravel deck get the same
    # sensitivity without a per-roof constant.
    #
    # The background is a CLIPPED local mean, not a local median. A median over a
    # 32 px window is O(n·k²) and scipy's is not separable: the first cut of this
    # bake was still measuring after 15 minutes and had not written a file. Two
    # separable uniform filters — mean, then mean again over only the pixels the
    # first pass called background — cost O(n), and reject the units' own
    # contribution to their own background, which is the only property the median
    # was there for.
    w = max(3, int(round(BG_M / res)) | 1)
    lz = np.where(good, luma, float(np.median(lv))).astype(np.float32)
    bg = ndimage.uniform_filter(lz, size=w, mode="nearest")
    s0 = np.abs(lz - bg)
    keep = s0 < max(DEV_FLOOR, 2.2 * float(np.median(s0[good])))
    num = ndimage.uniform_filter(np.where(keep, lz, 0.0).astype(np.float32), size=w, mode="nearest")
    den = ndimage.uniform_filter(keep.astype(np.float32), size=w, mode="nearest")
    bg = np.where(den > 0.15, num / np.maximum(den, 1e-6), bg)
    dev = lz - bg
    dv = dev[good]
    mad = float(np.median(np.abs(dv - np.median(dv)))) * 1.4826
    thr = min(DEV_CEIL, max(DEV_FLOOR, DEV_K * mad))
    eq = good & (np.abs(dev) > thr)
    # A blob is a thing plus its own shadow, and both matter for reading it, but
    # one pixel of noise is not a condenser. Close first (a unit and its shadow
    # are one object), then open (kill single-pixel speckle).
    eq = ndimage.binary_closing(eq, np.ones((3, 3)), border_value=0)
    eq = ndimage.binary_opening(eq, np.ones((2, 2)), border_value=0)
    eq &= good

    # Vegetation veto. A live oak overhanging a parapet is a big, green,
    # saturated blob and it is not roof plant.
    mx = f.max(axis=-1); mn = f.min(axis=-1)
    sat = np.where(mx > 1, (mx - mn) / np.maximum(mx, 1), 0.0)
    veg = (f[..., 1] >= f[..., 0]) & (f[..., 1] > f[..., 2]) & (sat > VEG_SAT)

    # Water. Rooftop pools really are everywhere in West Campus, and they are the
    # easiest thing in the whole scene to detect: nothing else on a roof is blue.
    water = good & (f[..., 2] > f[..., 0] + 10) & (f[..., 1] > f[..., 0] + 4) & \
        (sat > 0.14) & (luma > 55)
    water = ndimage.binary_opening(water, np.ones((3, 3)), border_value=0)

    th = dominant_axis(poly)
    ct, st = math.cos(-th), math.sin(-th)
    cell = res * res

    def blobs_from(mask, forced=None):
        lab, nlab = ndimage.label(mask)
        if nlab == 0:
            return []
        got = []
        for sl, i in zip(ndimage.find_objects(lab), range(1, nlab + 1)):
            m = (lab[sl] == i)
            n = int(m.sum())
            a = n * cell
            if a < MIN_BLOB_M2 or a > 2600:
                continue
            ys_, xs_ = np.nonzero(m)
            px = X[sl][m]; py = Y[sl][m]
            if forced is None and veg[sl][m].mean() > 0.45:
                continue
            # Oriented extent in the BUILDING's frame, not in north-up pixels.
            u = px * ct - py * st
            v = px * st + py * ct
            wdt = float(u.max() - u.min()) + res
            lng = float(v.max() - v.min()) + res
            if wdt < 0.35 or lng < 0.35:
                continue
            fill = a / max(wdt * lng, 1e-6)
            bl = f[sl][m]
            med = np.median(bl, axis=0)
            lm = float(0.299*med[0] + 0.587*med[1] + 0.114*med[2])
            ucx = float(u.mean()); vcy = float(v.mean())
            # back to world metres, then to centroid-relative
            wx = ucx * ct + vcy * st
            wy = -ucx * st + vcy * ct
            asp = max(wdt, lng) / max(0.4, min(wdt, lng))
            if forced:
                kind = forced
            elif asp >= 4.5 and min(wdt, lng) <= 2.6 and a >= 3.0:
                kind = "duct"
            elif a < 5.5 and max(wdt, lng) < 3.8:
                kind = "cond"
            elif a <= 30 and abs(wdt - lng) / max(wdt, lng) < 0.28 and fill > 0.68:
                kind = "fan"
            elif a < 34:
                kind = "unit"
            elif fill >= 0.60 and lm >= 100:
                kind = "phouse"
            else:
                kind = "plant"
            got.append({"k": kind, "x": round(wx - cx, 2), "y": round(wy - cy, 2),
                        "w": round(min(wdt, 44.0), 2), "l": round(min(lng, 44.0), 2),
                        "a": round(a, 1),
                        "c": [round(float(c), 1) for c in med], "lm": round(lm, 1)})
        return got

    got = blobs_from(eq)
    pools = blobs_from(water, forced="pool")
    # A pool is water first and a "unit" second; drop anything that overlaps one.
    for p in pools:
        got = [b for b in got
               if abs(b["x"] - p["x"]) > (b["w"] + p["w"]) * 0.4 or
                  abs(b["y"] - p["y"]) > (b["l"] + p["l"]) * 0.4]
    got += pools

    # A parking deck's "equipment" is parked cars. There is no colour rule that
    # separates a white sedan from a white AHU, so the deck's clutter is thrown
    # away wholesale and it gets stair cores by rule instead — which is what a
    # parking deck actually has on it.
    if is_parking:
        got = [b for b in got if b["k"] in ("phouse",) and b["a"] >= 25]

    got.sort(key=lambda b: -b["a"])
    out["blobs"] = got[:SURVEY_KEEP]
    out["theta"] = round(th, 5)
    out["drop"] = max(0, len(got) - SURVEY_KEEP)
    return out


# ── geometry ──────────────────────────────────────────────────────────
def box(cx, cy, w, l, th):
    ct, st = math.cos(th), math.sin(th)
    hw, hl = w / 2.0, l / 2.0
    pts = [(-hw, -hl), (hw, -hl), (hw, hl), (-hw, hl)]
    r = [(cx + x * ct - y * st, cy + x * st + y * ct) for (x, y) in pts]
    return r + [r[0]]


def h32(s):
    """Stable small hash — a generated overrun must land in the same corner on
    every bake, or a re-bake looks like the roofs moved."""
    v = 2166136261
    for ch in str(s).encode("utf-8"):
        v = ((v ^ ch) * 16777619) & 0xFFFFFFFF
    return v


def load_parking():
    """Multi-storey parking structures from the OSM cache, as metric polygons."""
    try:
        d = json.load(open(PARKING, encoding="utf-8"))
    except Exception:
        return []
    els = d["elements"] if isinstance(d, dict) else d
    nodes = {e["id"]: (e["lon"], e["lat"]) for e in els if e.get("type") == "node"}
    out = []
    for e in els:
        t = e.get("tags") or {}
        multi = t.get("parking") == "multi-storey" or t.get("building") in ("garage", "parking")
        if not multi:
            continue
        g = e.get("geometry")
        pts = [(p["lon"], p["lat"]) for p in g] if g else \
              [nodes[n] for n in (e.get("nodes") or []) if n in nodes]
        if len(pts) >= 4:
            lons = [p[0] for p in pts]; lats = [p[1] for p in pts]
            out.append((min(lons), min(lats), max(lons), max(lats)))
    return out


def main():
    report = "--report" in sys.argv
    remeasure = "--remeasure" in sys.argv or not os.path.exists(SURVEY)

    date = sorted(os.listdir(SNAPDIR))[-1]
    snap = os.path.join(SNAPDIR, date, "buildings.detailed.geojson")
    feats = json.load(open(snap, encoding="utf-8"))["features"]

    runs = json.load(open(RUNS, encoding="utf-8")) if os.path.exists(RUNS) else {}
    pitched = {k.split("/")[0] for k, v in runs.items() if v and v[0] >= MIN_RUN_PITCHED}
    garages = load_parking()
    # DKR is a ring 46,000 m^2 in plan, and app.js REPLACES its extrusion with a
    # perimeter wall plus seating bands because 82% of that plan is open seating,
    # not roof (see addStadiumLayers). A deck baked from the footprint would hang
    # a single enormous slab over the open bowl — the most visible possible bug
    # in the scene. Same document, same list.
    #
    # DKR was the FIRST building to need this and for two years it was the only
    # one hard-coded here, which quietly became wrong the day five building
    # passes landed at once. A pass that redraws a building at a height the
    # snapshot does not carry, or that authors its own penthouse and deck, owns
    # that building's roof — and this bake was still baking a generic one:
    #
    #   nine West Campus towers got a 0.25 m deck and a field of condensers
    #   hovering 1.0-1.1 m above their authored mechanical penthouses;
    #   the Moody Center got 253 features of arena plant standing ~2 m proud of
    #   its authored roof;
    #   PCL, the Bass/PAC and the ten Snohetta petals got decks buried metres
    #   down inside taller authored geometry, drawn on every frame for nothing.
    #
    # So the exclusion list is now DECLARED BY THE PASSES rather than hard-coded
    # here: any bake in data/ may carry `authoredRoofIds`. The stadium keeps
    # using `replacedBuildingIds` because app.js, not a bake script, owns it.
    # See docs/PASS_GLITCH.md.
    replaced = set()
    for fn in sorted(os.listdir(os.path.join(ROOT, "data"))):
        if not fn.endswith(".geojson"):
            continue
        try:
            gj = json.load(open(os.path.join(ROOT, "data", fn), encoding="utf-8"))
        except Exception:
            continue
        if fn == "stadium.geojson":
            replaced |= set(gj.get("replacedBuildingIds") or [])
        replaced |= set(gj.get("authoredRoofIds") or [])
    cache = {} if remeasure else json.load(open(SURVEY, encoding="utf-8"))

    out = []
    stats = Counter()
    rows = []
    for fi, f in enumerate(feats):
        # Checkpoint. Reading 2,400 roofs off z20 tiles takes ~15 minutes, and
        # losing all of it to one interrupted run (twice, while this was being
        # tuned) is exactly the waste the cache exists to prevent. A re-run
        # without --remeasure picks up every roof already in the file.
        if remeasure and fi and fi % 200 == 0:
            print("  measured %d/%d" % (fi, len(feats)), flush=True)
            with open(SURVEY, "w", encoding="utf-8") as fh:
                json.dump(cache, fh, separators=(",", ":"), sort_keys=True)
        p = f["properties"]
        bid = p.get("id")
        h = p.get("final_height") or 0
        if h < MIN_H:
            stats["too_short"] += 1
            continue
        if bid in pitched:
            stats["already_pitched"] += 1     # bake_roofs.py owns these
            continue
        if bid in replaced:
            stats["roof_authored_by_a_pass"] += 1
            continue
        if p.get("has_parts"):
            # parts-3d draws this building's real massing at its own heights, so
            # `final_height` is not where its roof is. Nine buildings.
            stats["has_parts"] += 1
            continue
        g = f["geometry"]
        rings = [g["coordinates"][0]] if g["type"] == "Polygon" else [q[0] for q in g["coordinates"]]
        ring = max(rings, key=len)
        if len(ring) < 4:
            continue
        lat0 = sum(q[1] for q in ring) / len(ring)
        lon0 = sum(q[0] for q in ring) / len(ring)
        name = (p.get("name") or "")
        if name in FOOTPRINT_OVERRIDDEN:
            stats["footprint_overridden_at_load"] += 1
            continue
        cls = p.get("building_class")
        is_park = (cls == "parking" or "garage" in name.lower() or
                   any(a <= lon0 <= c and b <= lat0 <= d for (a, b, c, d) in garages))

        key = str(bid)
        if key in cache:
            s = cache[key]
        else:
            s = survey(ring, lat0, p.get("rd"), is_park)
            cache[key] = s
        if not s:
            stats["no_imagery_or_too_small"] += 1
            continue

        # ── the deck ──────────────────────────────────────────────────
        # It sits ON the parapet cap app.js already draws (CAP_GEOM), inset by
        # PARAPET_IN, so the cap shows as a rim around it. Above rather than
        # inside for exactly the reason the cap itself sits on the wall instead
        # of in it: two coplanar faces with different colours is z-fighting, and
        # it is a phone's 16-bit depth buffer that pays for it.
        lift = max(1.0, 0.015 * h)
        deck_b = round(h + lift, 2)
        deck_h = round(deck_b + 0.25, 2)
        pm = clean(to_m(ring, lat0))
        dr = inset(pm, PARAPET_IN) or inset(pm, 0.55)
        if dr is None:
            stats["deck_degenerate"] += 1
            continue
        dr = ccw(dr)
        rd = temper(s["col"], p.get("rd"))
        deck_props = {
            "k": "deck", "src": "m", "t": 0, "d": 0.0,
            "b": deck_b, "h": deck_h,
            "rd": rd,
            "rg": like(rd, p.get("rd"), p.get("rg")),
            "rn": night_of(rd, p.get("rn")),
        }
        out.append({"type": "Feature",
                    "geometry": {"type": "Polygon", "coordinates": [to_ll(dr + [dr[0]], lat0)]},
                    "properties": deck_props})
        stats["decks"] += 1

        # ── the clutter ───────────────────────────────────────────────
        th = s.get("theta", 0.0)
        cxm, cym = s["c"]
        poly = ccw(pm)
        placed = 0
        biggest = 0.0
        draw = s["blobs"][:MAX_FOR(s["area"])]
        n = max(1, len(draw))
        # Rectangles already emitted on THIS roof, as (cx, cy, w, l, top), so a
        # second blob describing the same equipment field can be recognised.
        #
        # The detector labels connected components in a threshold mask, and a
        # big louvre screen with a gap down the middle comes back as two
        # components. Each is then drawn as its ORIENTED BOUNDING RECTANGLE, and
        # two bounding rectangles of two halves of one object are two ~identical
        # rectangles — same kind, so same KIND_H, so the SAME TOP HEIGHT. Two
        # coplanar top faces have no defined draw order, and the shared area
        # breaks into a comb of scanlines that flips as the camera moves.
        #
        # That shipped: the Flawn Academic Center carried two `plant` slabs at
        # 14.45-15.95 m sharing 94% of 1,887 m^2, and the whole roof visibly
        # glitched from the air. Nine roofs were affected. See docs/PASS_GLITCH.md.
        emitted = []
        for i, b in enumerate(draw):
            kind = b["k"]
            if kind == "pool":
                bc = b["c"]
                if (b["a"] < POOL_MIN_M2 or b.get("lm", 0) < POOL_MIN_LUMA or
                        (bc[2] - bc[0]) < POOL_MIN_BR):
                    stats["shadow_not_water"] += 1
                    continue
            w = max(0.8, b["w"]); l = max(0.8, b["l"])
            # A condenser's blob includes its own shadow, which at a 54 deg sun
            # is about half its width again. Shrinking the small kinds back is
            # the difference between a tidy row of units and a row of slabs.
            if kind in ("cond", "unit", "fan"):
                w *= 0.80; l *= 0.80
            ht = KIND_H.get(kind, 1.2)
            ccx, ccy = cxm + b["x"], cym + b["y"]
            # Never let a box hang over the parapet — a unit half off the roof is
            # the single most obviously wrong thing a generated roof can do.
            # But the first cut required `max(w,l)/2 + 0.35` of clearance and
            # threw away 2,387 units, most of them real: a West Campus condenser
            # row sits along the perimeter, a metre or two inside the parapet,
            # which is exactly where the strict test rejects it. The box only
            # has to fit on its SHORT axis to stay on the roof, and the deck is
            # already inset PARAPET_IN from the wall before this is measured.
            if clearance((ccx, ccy), poly) < min(w, l) * 0.5 + 0.25:
                stats["clipped_at_parapet"] += 1
                continue
            # Coplanar-duplicate guard. `draw` is sorted biggest-first, so the
            # survivor is always the larger reading of the object. Compared in
            # the roof's own frame: every box on this roof shares `th`, so
            # projecting the centre offset onto that frame's axes makes the two
            # rectangles axis-aligned with respect to each other and the overlap
            # exact rather than a bbox approximation.
            top_h = round(deck_h + ht, 2)

            def _shared(ox_, oy_, ow, ol):
                dx, dy = ccx - ox_, ccy - oy_
                du = abs(dx * math.cos(th) + dy * math.sin(th))
                dv = abs(-dx * math.sin(th) + dy * math.cos(th))
                return (max(0.0, (w + ow) / 2.0 - du) *
                        max(0.0, (l + ol) / 2.0 - dv))

            dup = False
            for _ in range(4):
                bump = False
                for (ox_, oy_, ow, ol, otop) in emitted:
                    if abs(otop - top_h) > 0.005:
                        continue
                    sh = _shared(ox_, oy_, ow, ol)
                    if sh <= 0.0:
                        continue
                    if sh >= COPLANAR_COVER * max(w * l, 1e-6):
                        dup = True
                        break
                    # A PARTIAL overlap is two different objects that happen to
                    # abut, so deleting one would delete something the
                    # photograph actually saw. Separate them in z instead: two
                    # adjacent equipment screens are not level in reality
                    # either, and 0.25 m is a sixth of a pixel from the flying
                    # camera while being far more than the depth buffer needs.
                    top_h = round(top_h + COPLANAR_STAGGER, 2)
                    bump = True
                    stats["coplanar_staggered"] += 1
                    break
                if dup or not bump:
                    break
            if dup:
                stats["coplanar_duplicate"] += 1
                continue

            lm = b.get("lm", 120)
            # Plant is metal and concrete: it lives in a narrower, cooler band
            # than the deck it stands on, and it must not out-shine a white
            # membrane roof or the roof reads as the shadow and the units as the
            # surface. Its own measured colour, mapped into that band.
            col = KIND_COL[kind] if lm < DARK_FLOOR else \
                temper(b["c"], p.get("rd"), toward=0.06, dst=(66, 168))
            if kind == "pool":
                col = KIND_COL["pool"]
            a = b["a"]
            tier = 0 if (a >= TIER0_M2 or ht >= TIER0_HT) else 1
            out.append({
                "type": "Feature",
                "geometry": {"type": "Polygon",
                             "coordinates": [to_ll(box(ccx, ccy, w, l, th), lat0)]},
                "properties": {
                    "k": kind, "src": "m", "t": tier,
                    # keep-order: 0 is always kept, 1 is dropped first. Biggest
                    # first, so turning the knob down thins the specks and keeps
                    # the plant that actually reads.
                    "d": round(i / n, 3),
                    "b": deck_h, "h": top_h,
                    "rd": col,
                    "rg": like(col, p.get("rd"), p.get("rg")),
                    "rn": night_of(col, p.get("rn")),
                },
            })
            emitted.append((ccx, ccy, w, l, top_h))
            placed += 1
            biggest = max(biggest, a)
            stats["k_" + kind] += 1

        # ── the one generated kind ────────────────────────────────────
        if h >= OVERRUN_MIN_H and biggest < 12.0:
            # Deepest point of the deck, offset toward a corner chosen by a hash
            # of the id so it is stable. Anything nearer the parapet than half
            # its own width would hang over the edge.
            # Sample the deck's interior on a coarse grid for the freest spot.
            best, bp = -1.0, None
            xs = [q[0] for q in dr]; ys = [q[1] for q in dr]
            hsh = h32(bid)
            for gi in range(7):
                for gj in range(7):
                    px_ = min(xs) + (max(xs) - min(xs)) * (gi + 0.5) / 7
                    py_ = min(ys) + (max(ys) - min(ys)) * (gj + 0.5) / 7
                    if not poly_mask(dr, np.array([[px_]]), np.array([[py_]]))[0, 0]:
                        continue
                    c = clearance((px_, py_), poly)
                    if c < max(OVERRUN_W, OVERRUN_L) * 0.5 + 0.6:
                        continue
                    # bias toward a corner, deterministically per building
                    bias = ((gi * 7 + gj) ^ hsh) % 13
                    score = c + bias * 0.11
                    if score > best:
                        best, bp = score, (px_, py_)
            if bp:
                out.append({
                    "type": "Feature",
                    "geometry": {"type": "Polygon",
                                 "coordinates": [to_ll(box(bp[0], bp[1], OVERRUN_W, OVERRUN_L, th), lat0)]},
                    "properties": {
                        "k": "phouse", "src": "g", "t": 0, "d": 0.0,
                        "b": deck_h, "h": round(deck_h + OVERRUN_HT, 2),
                        "rd": temper([168, 163, 152], p.get("rd"), toward=0.14),
                        "rg": like(temper([168, 163, 152], p.get("rd"), toward=0.14),
                                   p.get("rd"), p.get("rg")),
                        "rn": night_of(temper([168, 163, 152], p.get("rd"), toward=0.14),
                                       p.get("rn")),
                    },
                })
                stats["generated_overruns"] += 1

        if report:
            rows.append((s["area"], len(s["blobs"]), rd, s["tex"], name or "(unnamed)"))

    # TWO FILES, and the split is the LOD, not a tidy-up. Tier 1 — the individual
    # condensers and small ducts — is 8,000-odd features and roughly two thirds of
    # the bytes, and js/roofs.js does not draw any of it above z16.2. Shipping it
    # in the same document would make the flyover pay ~2.6 MB of download and
    # worker tiling for geometry it never shows. So the detail tier is its own
    # file and the module fetches it only when the camera first gets low enough
    # to want it. See ROOFS.minorMinZoom / ensureDetail() in js/roofs.js.
    base = [f for f in out if f["properties"]["t"] == 0]
    detail = [f for f in out if f["properties"]["t"] != 0]
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump({"type": "FeatureCollection", "features": base}, fh, separators=(",", ":"))
    with open(OUT_DETAIL, "w", encoding="utf-8") as fh:
        json.dump({"type": "FeatureCollection", "features": detail}, fh, separators=(",", ":"))
    with open(SURVEY, "w", encoding="utf-8") as fh:
        json.dump(cache, fh, separators=(",", ":"), sort_keys=True)

    meas = sum(1 for f in out if f["properties"]["src"] == "m")
    gen = len(out) - meas
    t0 = len(base)
    print(json.dumps({
        "snapshot": date,
        "features": len(out),
        "measured": meas, "generated": gen,
        "tier0_from_z14_5": t0, "tier1_from_z16_2": len(out) - t0,
        "base_kb": round(os.path.getsize(OUT) / 1024, 1),
        "detail_kb_lazy": round(os.path.getsize(OUT_DETAIL) / 1024, 1),
        "counts": dict(sorted(stats.items())),
        "provenance": {
            "deck colour": "MEASURED - median of the 55-90th luma percentile inside "
                           "the parapet, z20 Esri nadir, tempered to scene exposure",
            "clutter position/size/orientation/colour": "MEASURED - local-median "
                           "deviation blobs, oriented in the building's own frame",
            "clutter height": "GENERATIVE - a nadir photo cannot measure height; "
                              "each kind gets the height that kind of plant has",
            "stair overruns": "GENERATIVE - only where the photograph showed an "
                              "empty roof on a building >= %.0f m" % OVERRUN_MIN_H,
        },
    }, indent=2))
    if report:
        rows.sort(key=lambda r: -r[1])
        print("\n  area   n  deck      tex   building")
        for a, n_, c, t, nm in rows[:60]:
            print("  %5.0f %3d  %s  %.3f  %s" % (a, n_, c, t, nm[:44]))


if __name__ == "__main__":
    main()
